before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisEncryptYml
    - secure: IWKB4G8qnDRA5S1bM4JbryT78vkVHt2w3gnlcQ0yLkaNso19eAIqaULdEfhf5YTdegrSViNQPOrk9YR5nPhAWeBGlslz+1tOmOI+4B58BpQYqbVgKsdVH6uSaArb9Drk1pUyXu0qHX0sWnRsL5roJsJ1HVFgyFpVwmBieahTiBQ= # AES_256_KEY
    # this value is auto-created by shTravisEncryptYml
    # - AES_ENCRYPTED_SH: MmZmODZmNjM5ZDMyZTU3YThlOTUwN2VhNmMwZTYyMjk=PztQoyDEXYc3IEe4PsUgYGBOSvM3AIaOlhTfCUD8EERWIVmpN0o6AXUK87BUnOHlPtaF7TG0FSazfwB9ZdpBoMcIipie2EQbh/tNWSzOjPpWxY83PEilZDUxUggSiZjGQczSKjV2Vu0ZpoB3qGYq2nbg/JRUofg3PdEHD4wKfxKo4Ix8VKEJ7PC5chxqULdA17eefm+is474aCrZWDH8hkKQzK+I6k9bSQ/yoeZllha2rw12L6eOKDuImp+plULATln5QmSZhV8vYg8zVvb5Cp8T0nyDu+n4tb3PXpoAm6ktX/vDTZn0aJOFhjJA/as+G64PZEdge/Z2tiyCqGzKnLQ8QC+mwI0EtVCtsRQJ4paiAhAOPtJZUBCIU4aUnSzP64z0QIcJPK3fgrkly5fgC+zARWwMDFHNOoEVogoKxOngjZ8SgfotH18+JxwXpB/Z5hEwYtPUtrsIy6XBLdTLvKfaONS4EVWLRd5NSuHc/HJzbqJtJC5VCXXBBvfqUG31FTbUXptP+A5cexOXacGmj2jcrBJ7a7aTzMZDLbMIdcMyvvI5Fa7+zUHa+sH5X8N6NHv347WYnQ+/TS4gW9v7xdsXYx+TdxE0zoiRyqkqHknZ4D/Wcgq1vRgG759lvC6pOHrZnCZ+tgmnyinHyP1k9tTvU1h+oo8+FH8g1hxDxzqKMBdw10hL79K4DrkQPByuNKViAMnRampFf5NfVHGQdMvvfMtYxd4PRkc5Uzg7tcXYplmN3o6ZmRCrh71kXgFL7DQiuFVnYtv5p5qOBWKcjVE38Z6l+TIdeoH+KXU5Z2Lciw6g/+dUPr5Qnlvz6DM1JOpK5+jdKr7tT/w3m3dCCSoUBi1nHVTiphd5GKQueAA= # AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
