before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisEncryptYml
    - secure: y6awgmYMyEOMOlzOvh7/spHWhBnBcEIvthzMR/Al20FnrnibJra9JA6Yx++V9GVMmz/ucoBadLBk6vJU79/meW8UHk2tb5MNGkIdhexvAhNnD0aMUXmHJdtPTEbwrQPx77gkZGHsD6mRNb9fKc8S7muqd2Z2E3ua4yR+8LHmn/8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: MDk0YWRiNDhjZmYzN2MxNDQ5NWNkNTVlZDliYjMwZDk=UaqWTrUhtFScP658DGqjrJlCOKFuqZyhUTW5OZmdj89noO/uA/xV40tTWuZAw5lNuFr+ihXVhUoZJ8d0Tw0RXIrQnFFu5Y7QhYLHu74dN/bWLKUcm0pvjgqlgfDIrfNx6Ud3ewlbw73yjDHL9scq2VKlWysBZRsYmVSJDN/HS98QCavSPcgKFFAsxtD+4yvgucNHOGnV5DGM3g7nD8niB2zFtDwXIp4zApXEKsS5AQyoNH7ZFeDugp/fMVLTlUMA/O6NdcPk23Qh+DBi5Xqtu2e/sXoTLgZSnqUbKGUtCkni/4LrWoSr5IxxGWgrMM3fE6dETnhtVpn1hLKZtGQ0LbfjFiopBbyZGxDOFrPWTr/MxXhhalhYIgWwbf0Sy39T48imR00Ac647SMfck9QMUpSo3l7IgtDyejYvxEUHYR1/i86aDUIkHf+KC0q2Sa8zY7vN/CzW+KOxvHiFBfG5yC2yq4rEqCAEDwY0mkz4YHSStaAtUQMK0NL89DnhlVy9zMaEuFKRL1QE1QTI+6BapUPb+cXy4NAS0N5CQ7xG0UKMKMyOoU9IxEaZvfqfqmEGJaqNK0EXl0iKSmcHr8hdZhQSI3fuzR5wkyE821GLXITilJXWjK0gmUZTq+HIvCckC1k/6y0kYZOSq6aZimPLAOIKNsaD/XbdKOsLJKV9duNPmlfX87FJMEx1jlEne1tYMM2fGNIKnzWUw0BkrAU2NEYrC/NsOOGLZmckxnN3iJUFty60jRKRwNhnyRCX8AN+fwrTych/CfI83BsSAgIWh12jjHk6fVDXnrviQiCpQYKDZzjdUe9ASEILzeSkPiDTuyTP8CZGolJvVX86QtDhS16V9pJ7KKSG4QHaBCoqEUM= # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
