before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: JDnQDSqPmY6v4ay976iLbibl0Vg3KH7yl6yhzTQ8/hJS2MzcARvdlDbhpBGGCcg/cciMZ2zZ4f8VpkIXOw3Gd87JdQIaPySbrZdJ9HQmRIa4ey16Y/bM5FglH6sQc0KucXHZsUXVwq6VXirm5RJXiuYhejbT6li/zkJDql99L54= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: NzlkMTMyZGVlN2ZmMjg2YjFmZDNiMjgwOGEwZDZiNWQ=Q5IUhNmjU/PkfhNj+N+2aex26C6DdULYudnJVRjWtDBrfxkVdxzkWMdkF56/5en9PLnPhIMPaFD6gvg8U4BxWr3syacjjiiUhEU3UCX94ZPAuQbuVc377JJbxeHvJhfKtQLStb3A/5eGbv+39ss3EgMwXKwP8nKNYcPtwmMOgRgo881SbXObNq/V4L6/xTqQNkdO+TuZ9CEc93/FTm3vnvNhDeIdcu3nGzcCYRsPkXjRwkGO/VeVYP66Nbx1177W4lrCTo0mwZSlZnF8otKaV/unLAJ+BMYYAVQhU4HKsnvVeCZslPfaDj1DsnqnskEIvs2b7o8E3PFSLD5sV/CYEViE6LGiK7OJr+BMWehCecXuT69frbc8/NCMCMmC35qcG6y6fduDbfzODfFjrL880BZ3pocViDwb1qcM3NQA7i9qbWcjLhchiNflAJMg8siE/wvkCwJq73//1Y7tC75SD4BuH784I3alz3xpF17r7AevA6JaWs8L9Ki+gesHO2CeS0qqCGWAQoKtLRwTI9sYkDoNmshMBhHzdjuaWJN9Oc4aJiW9cayfxTIWsPgzcFk4owUExZeKTEmXimalUyx7FXWZYqaCHhHMT+ZC2J9aVT0Ph5kQD00m5aMTA5t+/MdEqFmAOaLpCwYUlXB2pwH/YlpolAgXI4X5fOYQXtolui0WeIzeI8XH9FDDm0EPICf3HQ7BK1D6GQgtxCh5tp00S67JALr71e0q30ZXj1KHTLHam8vXeUh9xMdsC64EnOHcqeLJ/FwCCoJJXKzyZCMHdzPaGfdYMvL4qAvmNcCUYmiY0rj/eBIgznD9qhq4A7O1nuXEmFbb+SVezPDNyBc4mCDArbXVdNGmCysnYdM7iH21JwUobVzYtsThDy4dfG6C1xPx64SLZPcUEgd762X2zGcgx20UaVsQSqnjNUva2qvprF/hDBGJ89FzMxafrNjoR+M2AWW9os9lj3I3dfsnuMjweUQFsgd7McV4AuQ6pnis1wgvdjcSYSyOSZVg4Aisc4C56bMWAr+nJKBEhDadVw== # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
